"""Prepare the publisher's free production PNGs; source ZIP stays outside the game.

python scripts/import-predator-plants.py [path/to/free-predator-plant-mobs-pixel-art-pack.zip]
"""
import hashlib
import io
import json
from pathlib import Path
import sys
import zipfile
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / 'test-results/asset-imports/free-predator-plant-mobs-pixel-art-pack.zip'
HASH = '2a2bc7637d203a6e852a877c090ca8d2b618ce47d6f92786a60ba1ae1e8da41f'
assert hashlib.sha256(SOURCE.read_bytes()).hexdigest() == HASH, 'Archive changed: inspect before importing.'
OUT = ROOT / 'public/game-assets/predator-plants'
OUT.mkdir(parents=True, exist_ok=True)
assets = {}
actions = {'idle': ('Idle', 800), 'walk': ('Walk', 720), 'attack': ('Attack', 840), 'hurt': ('Hurt', 300), 'death': ('Death', 1100)}
with zipfile.ZipFile(SOURCE) as archive:
    for number, kind in enumerate(['venus-trap', 'blue-death', 'root-beast'], 1):
        frames, animations = [], {}
        for action, (folder, duration) in actions.items():
            member = f'PNG/Plant{number}/{folder}/Plant{number}_{folder}_full.png'
            sheet = Image.open(io.BytesIO(archive.read(member))).convert('RGBA')
            assert sheet.height == 256 and sheet.width % 64 == 0
            directions = {}
            for row, direction in enumerate(['down', 'up', 'left', 'right']):
                directions[direction] = []
                for column in range(sheet.width // 64):
                    frame = sheet.crop((column * 64, row * 64, column * 64 + 64, row * 64 + 64))
                    assert frame.getbbox(), (member, row, column)
                    directions[direction].append(len(frames))
                    frames.append(frame)
            animations[action] = {'durationMs': duration, 'loop': action in ('idle', 'walk'), 'frames': directions}
            if action == 'attack':
                animations[action]['impactAtMs'] = 480  # column 4: native contact / mouth release
        atlas = Image.new('RGBA', (512, ((len(frames) + 7) // 8) * 64))
        for index, frame in enumerate(frames):
            atlas.paste(frame, ((index % 8) * 64, (index // 8) * 64))
        atlas.save(OUT / f'{kind}.png', optimize=True)
        assets[kind] = {'id': kind, 'textureKey': f'predator-{kind}', 'imageUrl': f'/game-assets/predator-plants/{kind}.png',
            'sourceUrl': 'https://craftpix.net/freebies/free-predator-plant-mobs-pixel-art-pack/',
            'author': 'CraftPix / Free Game Assets (GUI, Sprite, Tilesets)',
            'license': 'CraftPix Freebie Products License (game use)', 'licenseUrl': '/game-assets/predator-plants/LICENSE-CraftPix.txt',
            'frameWidth': 64, 'frameHeight': 64, 'columns': 8, 'frameCount': len(frames),
            'feet': {'x': 32, 'y': 48}, 'origin': {'x': 0.5, 'y': 0.75}, 'suggestedScale': 2,
            'animations': animations, 'animationNotes': ['Unmodified production pixels, including source shadows. Rows: front, back, left, right.',
                '64px cells share a fixed (32,48) ground anchor; animation timing is game-authored. Native contact is column 4.',
                'Run layers remain in the source archive; walk drives ordinary movement.']}

(OUT / 'LICENSE-CraftPix.txt').write_text((ROOT / 'public/game-assets/magic-demo/LICENSE-CraftPix.txt').read_text(encoding='utf8'), encoding='utf8')
(OUT / 'CREDITS.md').write_text('# Predator plants\n\nCraftPix / Free Game Assets (GUI, Sprite, Tilesets).\n\n'
    'Source: https://craftpix.net/freebies/free-predator-plant-mobs-pixel-art-pack/\n'
    'Publisher download: https://free-game-assets.itch.io/free-predator-plant-mobs-pixel-art-pack\n'
    'License: https://craftpix.net/file-licenses/ — freebie game use, including commercial projects. '
    'Do not redistribute these files as a standalone asset pack.\n\n'
    'Production PNG cells repacked without repainting or mirroring. Three plants, five actions, four directions.\n', encoding='utf8')
(OUT / 'provenance.json').write_text(json.dumps({'archive': SOURCE.name, 'sha256': HASH, 'assets': assets}, indent=2) + '\n', encoding='utf8')
(ROOT / 'src/features/rpg/adventure/plant-assets.ts').write_text(
    '// Generated by scripts/import-predator-plants.py; native production animation cells.\n'
    "import type { JungleWildlifeAsset } from '../demo/wildlife-assets';\n"
    "export type PlantKind = 'venus-trap' | 'blue-death' | 'root-beast';\n"
    "export type PlantAsset = Omit<JungleWildlifeAsset, 'id'> & { id: PlantKind };\n"
    'export const PLANT_ASSETS: Readonly<Record<PlantKind, PlantAsset>> = ' + json.dumps(assets, indent=2) + ';\n', encoding='utf8')
print('Imported', len(assets), 'plants:', len(frames), 'real frames each')
