// Generated by scripts/import-weapon-demo.py from native production animation strips.
import type { JungleWildlifeAsset } from './wildlife-assets';

export type ForestEnemyId = 'forest-brute' | 'forest-skirmisher';
export type ForestEnemyAsset = Omit<JungleWildlifeAsset, 'id'> & { id: ForestEnemyId };

export const FOREST_ENEMY_ASSETS: Readonly<Record<ForestEnemyId, ForestEnemyAsset>> = {
  'forest-brute': {
    id: 'forest-brute',
    textureKey: 'weapon-demo-forest-brute',
    imageUrl: '/game-assets/weapon-demo/forest-brute.png',
    sourceUrl: 'https://craftpix.net/freebies/free-forest-bosses-pixel-art-sprite-sheet-pack/',
    author: 'CraftPix / Free Game Assets (GUI, Sprite, Tilesets)',
    license: 'CraftPix Freebie Products License (game use)',
    licenseUrl: '/game-assets/weapon-demo/LICENSE-CraftPix.txt',
    frameWidth: 80,
    frameHeight: 48,
    columns: 8,
    frameCount: 52,
    feet: {
      x: 40,
      y: 48,
    },
    origin: {
      x: 0.5,
      y: 1,
    },
    suggestedScale: 2,
    animations: {
      idle: {
        durationMs: 800,
        loop: true,
        frames: {
          left: [0, 1, 2, 3],
          right: [4, 5, 6, 7],
          up: [4, 5, 6, 7],
          down: [4, 5, 6, 7],
        },
      },
      walk: {
        durationMs: 600,
        loop: true,
        frames: {
          left: [8, 9, 10, 11, 12, 13],
          right: [14, 15, 16, 17, 18, 19],
          up: [14, 15, 16, 17, 18, 19],
          down: [14, 15, 16, 17, 18, 19],
        },
      },
      attack: {
        durationMs: 780,
        loop: false,
        frames: {
          left: [20, 21, 22, 23, 24, 25],
          right: [26, 27, 28, 29, 30, 31],
          up: [26, 27, 28, 29, 30, 31],
          down: [26, 27, 28, 29, 30, 31],
        },
        impactAtMs: 520,
      },
      hurt: {
        durationMs: 240,
        loop: false,
        frames: {
          left: [32, 33, 34, 35],
          right: [36, 37, 38, 39],
          up: [36, 37, 38, 39],
          down: [36, 37, 38, 39],
        },
      },
      death: {
        durationMs: 780,
        loop: false,
        frames: {
          left: [40, 41, 42, 43, 44, 45],
          right: [46, 47, 48, 49, 50, 51],
          up: [46, 47, 48, 49, 50, 51],
          down: [46, 47, 48, 49, 50, 51],
        },
      },
    },
    animationNotes: [
      'Purple-marked forest fighter, character 2 from the separately licensed animated forest bosses pack; not from the requested modular vector tribal pack.',
      'Source faces left. Right frames are exact horizontal mirrors; up/down reuse the right side view.',
      'Constant empty margins removed without clipping any source alpha. Shared foot anchor is (40,48) in 80x48 cells.',
      'Only the listed real frame indices are playable; transparent atlas padding is excluded.',
      'Cycle and impact timing are demo choices rather than author-provided timings.',
    ],
  },
  'forest-skirmisher': {
    id: 'forest-skirmisher',
    textureKey: 'weapon-demo-forest-skirmisher',
    imageUrl: '/game-assets/weapon-demo/forest-skirmisher.png',
    sourceUrl: 'https://craftpix.net/freebies/free-forest-bosses-pixel-art-sprite-sheet-pack/',
    author: 'CraftPix / Free Game Assets (GUI, Sprite, Tilesets)',
    license: 'CraftPix Freebie Products License (game use)',
    licenseUrl: '/game-assets/weapon-demo/LICENSE-CraftPix.txt',
    frameWidth: 80,
    frameHeight: 48,
    columns: 8,
    frameCount: 48,
    feet: {
      x: 40,
      y: 48,
    },
    origin: {
      x: 0.5,
      y: 1,
    },
    suggestedScale: 2,
    animations: {
      idle: {
        durationMs: 800,
        loop: true,
        frames: {
          left: [0, 1, 2, 3],
          right: [4, 5, 6, 7],
          up: [4, 5, 6, 7],
          down: [4, 5, 6, 7],
        },
      },
      walk: {
        durationMs: 600,
        loop: true,
        frames: {
          left: [8, 9, 10, 11, 12, 13],
          right: [14, 15, 16, 17, 18, 19],
          up: [14, 15, 16, 17, 18, 19],
          down: [14, 15, 16, 17, 18, 19],
        },
      },
      attack: {
        durationMs: 660,
        loop: false,
        frames: {
          left: [20, 21, 22, 23, 24, 25],
          right: [26, 27, 28, 29, 30, 31],
          up: [26, 27, 28, 29, 30, 31],
          down: [26, 27, 28, 29, 30, 31],
        },
        impactAtMs: 440,
        windupEndAtMs: 220,
      },
      hurt: {
        durationMs: 240,
        loop: false,
        frames: {
          left: [32, 33, 34, 35],
          right: [36, 37, 38, 39],
          up: [36, 37, 38, 39],
          down: [36, 37, 38, 39],
        },
      },
      death: {
        durationMs: 600,
        loop: false,
        frames: {
          left: [40, 41, 42, 43],
          right: [44, 45, 46, 47],
          up: [44, 45, 46, 47],
          down: [44, 45, 46, 47],
        },
      },
    },
    animationNotes: [
      'Yellow-marked forest caster, character 3 from the separately licensed animated forest bosses pack; not from the requested modular vector tribal pack.',
      'Source faces left. Right frames are exact horizontal mirrors; up/down reuse the right side view.',
      'Constant empty margins removed without clipping any source alpha. Shared foot anchor is (40,48) in 80x48 cells.',
      'Only the listed real frame indices are playable; transparent atlas padding is excluded.',
      'Cycle and impact timing are demo choices rather than author-provided timings.',
      'Standing cast: preparation plays during windup; the bright-hand frame releases 3/Projectile.png.',
    ],
  },
};
