// Generated by scripts/import-weapon-demo.py; gameplay statistics live in equipment.ts.
export type WeaponItemFamily = 'sword' | 'axe' | 'spear' | 'staff';
export type WeaponItemTier = 0 | 1 | 2 | 3 | 4 | 5;
export interface WeaponItemAsset {
  id: `${WeaponItemFamily}-${WeaponItemTier}`;
  name: string;
  family: WeaponItemFamily;
  tier: WeaponItemTier;
  imageUrl: string;
}

/** Static inventory art by Truly Malicious, CC BY 4.0; credits in weapon-demo/CREDITS.txt. */
export const WEAPON_ITEM_ASSETS: readonly WeaponItemAsset[] = [
  {
    id: 'sword-0',
    name: 'Practice sword',
    family: 'sword',
    tier: 0,
    imageUrl: '/game-assets/weapon-demo/sword-0.png',
  },
  {
    id: 'sword-1',
    name: 'Wooden sword',
    family: 'sword',
    tier: 1,
    imageUrl: '/game-assets/weapon-demo/sword-1.png',
  },
  {
    id: 'sword-2',
    name: 'Iron sword',
    family: 'sword',
    tier: 2,
    imageUrl: '/game-assets/weapon-demo/sword-2.png',
  },
  {
    id: 'sword-3',
    name: 'Bronze sword',
    family: 'sword',
    tier: 3,
    imageUrl: '/game-assets/weapon-demo/sword-3.png',
  },
  {
    id: 'sword-4',
    name: 'Silver sword',
    family: 'sword',
    tier: 4,
    imageUrl: '/game-assets/weapon-demo/sword-4.png',
  },
  {
    id: 'sword-5',
    name: 'Gold sword',
    family: 'sword',
    tier: 5,
    imageUrl: '/game-assets/weapon-demo/sword-5.png',
  },
  {
    id: 'axe-0',
    name: 'Practice axe',
    family: 'axe',
    tier: 0,
    imageUrl: '/game-assets/weapon-demo/axe-0.png',
  },
  {
    id: 'axe-1',
    name: 'Woodcutter axe',
    family: 'axe',
    tier: 1,
    imageUrl: '/game-assets/weapon-demo/axe-1.png',
  },
  {
    id: 'axe-2',
    name: 'Iron axe',
    family: 'axe',
    tier: 2,
    imageUrl: '/game-assets/weapon-demo/axe-2.png',
  },
  {
    id: 'axe-3',
    name: 'Bronze axe',
    family: 'axe',
    tier: 3,
    imageUrl: '/game-assets/weapon-demo/axe-3.png',
  },
  {
    id: 'axe-4',
    name: 'Silver axe',
    family: 'axe',
    tier: 4,
    imageUrl: '/game-assets/weapon-demo/axe-4.png',
  },
  {
    id: 'axe-5',
    name: 'Gold axe',
    family: 'axe',
    tier: 5,
    imageUrl: '/game-assets/weapon-demo/axe-5.png',
  },
  {
    id: 'spear-0',
    name: 'Practice spear',
    family: 'spear',
    tier: 0,
    imageUrl: '/game-assets/weapon-demo/spear-0.png',
  },
  {
    id: 'spear-1',
    name: 'Wooden spear',
    family: 'spear',
    tier: 1,
    imageUrl: '/game-assets/weapon-demo/spear-1.png',
  },
  {
    id: 'spear-2',
    name: 'Iron spear',
    family: 'spear',
    tier: 2,
    imageUrl: '/game-assets/weapon-demo/spear-2.png',
  },
  {
    id: 'spear-3',
    name: 'Bronze spear',
    family: 'spear',
    tier: 3,
    imageUrl: '/game-assets/weapon-demo/spear-3.png',
  },
  {
    id: 'spear-4',
    name: 'Silver spear',
    family: 'spear',
    tier: 4,
    imageUrl: '/game-assets/weapon-demo/spear-4.png',
  },
  {
    id: 'spear-5',
    name: 'Gold spear',
    family: 'spear',
    tier: 5,
    imageUrl: '/game-assets/weapon-demo/spear-5.png',
  },
  {
    id: 'staff-0',
    name: 'Practice staff',
    family: 'staff',
    tier: 0,
    imageUrl: '/game-assets/weapon-demo/staff-0.png',
  },
  {
    id: 'staff-1',
    name: 'Wooden staff',
    family: 'staff',
    tier: 1,
    imageUrl: '/game-assets/weapon-demo/staff-1.png',
  },
  {
    id: 'staff-2',
    name: 'White staff',
    family: 'staff',
    tier: 2,
    imageUrl: '/game-assets/weapon-demo/staff-2.png',
  },
  {
    id: 'staff-3',
    name: 'Bronze staff',
    family: 'staff',
    tier: 3,
    imageUrl: '/game-assets/weapon-demo/staff-3.png',
  },
  {
    id: 'staff-4',
    name: 'Silver staff',
    family: 'staff',
    tier: 4,
    imageUrl: '/game-assets/weapon-demo/staff-4.png',
  },
  {
    id: 'staff-5',
    name: 'Gold staff',
    family: 'staff',
    tier: 5,
    imageUrl: '/game-assets/weapon-demo/staff-5.png',
  },
];
