// Generated by scripts/import-ruined-temple.py.
import type { RpgTexture } from '../types';
export const TEMPLE_TEXTURES: RpgTexture[] = [
  {
    key: 'temple-sanctuary',
    url: '/game-assets/ruined-temple/sanctuary.png',
  },
  {
    key: 'temple-foundation',
    url: '/game-assets/ruined-temple/foundation.png',
  },
  {
    key: 'temple-arch',
    url: '/game-assets/ruined-temple/arch.png',
  },
  {
    key: 'temple-statue',
    url: '/game-assets/ruined-temple/statue.png',
  },
  {
    key: 'temple-broken-statue',
    url: '/game-assets/ruined-temple/broken-statue.png',
  },
  {
    key: 'temple-column',
    url: '/game-assets/ruined-temple/column.png',
  },
  {
    key: 'temple-broken-column',
    url: '/game-assets/ruined-temple/broken-column.png',
  },
  {
    key: 'temple-tree-broad',
    url: '/game-assets/ruined-temple/tree-broad.png',
  },
  {
    key: 'temple-tree-pine',
    url: '/game-assets/ruined-temple/tree-pine.png',
  },
  {
    key: 'temple-tree-round',
    url: '/game-assets/ruined-temple/tree-round.png',
  },
  {
    key: 'temple-bush',
    url: '/game-assets/ruined-temple/bush.png',
  },
  {
    key: 'temple-wall',
    url: '/game-assets/ruined-temple/wall.png',
  },
  {
    key: 'temple-vines',
    url: '/game-assets/ruined-temple/vines.png',
  },
  {
    key: 'temple-flagstone',
    url: '/game-assets/ruined-temple/flagstone.png',
  },
  {
    key: 'temple-rubble',
    url: '/game-assets/ruined-temple/rubble.png',
  },
  {
    key: 'temple-urns',
    url: '/game-assets/ruined-temple/urns.png',
  },
  {
    key: 'temple-flame',
    url: '/game-assets/ruined-temple/flame.png',
    frameWidth: 32,
    frameHeight: 40,
  },
];
